site_name: Hexital
site_url: https://MerlinR.github.io/Hexital
repo_name: merlinr/hexital
repo_url: https://github.com/MerlinR/Hexital
site_author: Merlinr
edit_uri: blob/master/docs/
site_description: Hexital - Incremental Technical Analysis Library
copyright: Copyright &copy; 2024 Merlinr
theme:
  name: material
  icon:
    logo: material/hexagon-outline
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: yellow
      accent: white
  features:
    - navigation.tabs
    - navigation.footer
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append: ["../LICENSE", "../CHANGELOG.md"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  

plugins:
- search
- link-marker
- section-index
- git-revision-date-localized
- gen-files:
    scripts:
      - docs/scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          paths: [ src ]
          options:
            line_length: 80
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            show_if_no_docstring: false
            filters: [ "!^_" ]
            heading_level: 2
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_docstring_modules: true
            modernize_annotations: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
- mike

extra:
  version:
    provider: mike
    default:
      - latest

nav:
  - Hexital: index.md
  - Features: features.md
  - Guides:
    - Quick Start: guides/quick-start.md
    - Indicators: guides/indicators-indepth.md
    - Candles: guides/candles.md
    - Hexital Strategy: guides/hexital-indepth.md
    - Indicator Analysis: guides/analysis-indepth.md
    - Candlesticks: guides/candlesticks.md
    # - Amorph Indicator: guides/amorph.md
    - Creating Indicator: guides/custom-indicator.md
  - Indicator's: indicator-catalogue.md
  - Catalogues:
    - Indicator's: indicator-catalogue.md
    - Candle Pattern's: candle-pattern-catalogue.md
    - Candlestick's - Beta: candlesticks-catalogue.md
    - Analysis Functions: analysis-catalogue.md
  - API Reference:
    - Reference: reference/index.md
    - API: reference/
  - About:
    - Design and Future: about/design.md
    - Alternatives: about/alternatives.md
  - Issue Tracker: https://github.com/MerlinR/Hexital/issues
  - Release Notes: changelog.md
