[project]
name = "hexital"
version = "4.0.1"
description = "Hex Incremental Technical Analysis Library"
authors = [{ name = "Merlin Roe", email = "merlin.roe@hotmail.co.uk" }]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
keywords = ["candles", "trading", "quant", "indicators", "Analysis", "Finance"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/MerlinR/Hexital"
Repository = "https://github.com/MerlinR/Hexital"
Documentation = "https://github.com/MerlinR/Hexital"

[dependency-groups]
dev = [
    "coverage",
    "ruff",
    "pytest",
    "pytest-cov",
    "pytest-profiling",
    "snakeviz",
]
truth = ["pandas", "numpy==1.26.4", "ta-lib", "pandas-ta"]
speed_tests = ["matplotlib", "pandas", "numpy==1.26.4", "ta-lib", "pandas-ta"]

docs = [
    "mkdocs-material==9.7.7",
    "mkdocstrings-python==2.0.7",
    "mkdocs-git-revision-date-localized-plugin==1.5.4",
    "mkdocs-link-marker==0.3.0",
    "mkdocs-gen-files==0.6.1",
    "mkdocs-literate-nav==0.6.3",
    "black==26.5.1",
    "mkdocs-section-index==0.3.12",
    "mike==2.2.0",
]

[tool.uv]
default-groups = ["dev"]

[tool.uv.sources]
pandas-ta = { git = "https://github.com/MerlinR/Pandas-ta-fork.git#master" }

[tool.coverage.run]
source = ["hexital"]
omit = ["tests/*", "benchmarks/*"]

[tool.coverage.report]
omit = ["tests/*", "benchmarks/*"]

[tool.hatch.build]
include = ["hexital/**", "./*"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
